### ISSUE TITLE
Players do not get cholera from drinking from ponds when HREG is installed

### ISSUE THREAD

**Issue by tjensen** [davidou2a/HellRetex_Official#115] opened 2022-01-23 16:24 UTC
**Describe the bug**
Players do not become infected with cholera after drinking directly from ponds and streams when HellRetex Enhanced Gameplay - Stable is installed on a server. However, filling a bottle at a pond/stream and drinking from the bottle (without purifying it, first) *does* give the player cholera.

**To Reproduce**
1. Start as a fresh spawn with 50% energy and hydration (not strictly necessary, but it avoids interference from immunity)
2. Find the nearest pond or stream
3. Drink directly from pond or stream until stomach is full
4. Wait for the illness icon to appear on the HUD (it won't)

In addition, the following error is logged repeatedly while a player is drinking from a pond:
```
SCRIPT    (E): NULL pointer to instance
Class:      'HREG_DietSystem_Handler'
Function: 'DietBadFoodLevelOne'
Stack trace:
H2A/HREG/Scripts/4_World/Classes/Ð¬*Ñ�Ñ‰.jpg:165
H2A/HREG/Scripts/4_World/Entities/ManBase/*ÐºÐ»Ñ™ÐµÑ˜Ð·ÑœÐ²Ñš.fxy:491
scripts/4_World/classes\useractionscomponent\actions\continuous\actiondrinkpondcontinuous.c:70
scripts/4_World/classes\useractionscomponent\actions\actioncontinuousbase.c:216
scripts/4_World/classes\useractionscomponent\actioncomponents\cacontinuousbase.c:12
scripts/4_World/classes\useractionscomponent\actioncomponents\cacontinuousrepeat.c:46
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:66
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:363
scripts/4_World/classes\useractionscomponent\actions\actioncontinuousbase.c:28
```

**Expected behavior**
A player without any immunity should acquire cholera after drinking directly from a pond or stream.

**Screenshots/video**
N/A

**Server or Client (please complete the following information):**
 The issue is :
- On server side

**Additional context**
N/A

**Comment by davidou2a** [comment] 2022-01-27 22:18
Hello isn't a bug, Cholera is Vanilla and not affected by HREG.

**Comment by tjensen** [comment] 2022-01-27 22:50
Hi @davidou2a. I know that cholera is vanilla. Drinking from a pond on vanilla gives the player cholera, but if HREG is installed, then the player *does not* get cholera.

Are you saying that it is a feature of HREG to disable cholera? If not, please check my steps to reproduce.

Thanks.

**Comment by davidou2a** [comment] 2022-01-27 23:09
Since HREG dont touch Cholera and vanilla dicease it's not necessary to trying to reproduce, it's a waste of time for me. Cholera is not systematic it's random chances.

**Comment by tjensen** [comment] 2022-01-27 23:12
@davidou2a I believe the error included in the description is the cause of HREG breaking cholera.

The error occurs in `PlayerBase.Consume`, which HREG has modded, and the error occurs **before** HREG calls `super.Consume`, which means the error prevents the vanilla code (which handles cholera) from running.

**Comment by tjensen** [comment] 2022-01-27 23:25
Here's a quick fix:

```diff
--- a/PlayerBase.c
+++ b/PlayerBase.c
@@ -488,10 +488,13 @@
 	 */
 	override bool Consume(ItemBase source, float amount, EConsumeType consume_type )
 	{
-		Get_HREG_DietSystem_Handler().DietBadFoodLevelOne(source, amount);
-		Get_HREG_DietSystem_Handler().DietBadFoodLevelTwo(source, amount);
-		Get_HREG_DietSystem_Handler().DietGoodFoodLevelOne(source, amount);
-		Get_HREG_DietSystem_Handler().DietGoodFoodLevelTwo(source, amount);
+		if (source)
+		{
+			Get_HREG_DietSystem_Handler().DietBadFoodLevelOne(source, amount);
+			Get_HREG_DietSystem_Handler().DietBadFoodLevelTwo(source, amount);
+			Get_HREG_DietSystem_Handler().DietGoodFoodLevelOne(source, amount);
+			Get_HREG_DietSystem_Handler().DietGoodFoodLevelTwo(source, amount);
+		}
 				
 		return super.Consume(source, amount, consume_type);
 	}
```

**Comment by davidou2a** [comment] 2022-01-28 06:55
ok, i will add this on the next update.
Thx.

**Comment by davidou2a** [comment] 2022-01-28 08:33
Fix pushed with another one.
I close the issue but not the discussion just say me if you have again the cholera issue.

Have a nice day.

**Closed** 2022-01-28 08:33 UTC
Labels: bug, fix soon
