### ISSUE TITLE
Tiredness meter decreasing to fast with Duration at Default value 14400.0

### ISSUE THREAD

**Issue by gilliegamer93** [davidou2a/HellRetex_Official#102] opened 2021-11-07 23:02 UTC
Has anyone else experienced this issue after last update?

**Comment by davidou2a** [comment] 2021-11-07 23:32
See issue #100Le 8 nov. 2021 00:02, gilliegamer93 ***@***.***> a écrit :
Assigned #102 to @davidou2a.

**Comment by SilverOcircle** [comment] 2021-11-08 06:23
Hello davidou2a, it's me again. You are probably already annoyed to hear from me. I don't want to offend you, but somehow I have the feeling that something doesn't fit right. Fatigue sets in at around 12 minutes. The last test I did I did with 43,200 as a setting. Even so, the display was blank after 10-12 minutes. It feels as if all settings have not been adopted for more than 10 minutes. You may find time to take a test with a 60 minute setting. You don't have to make a video effort either. Just to be sure.

**Comment by MATTvanEAGLE** [comment] 2021-11-08 10:23
I have to contribute the same with the HREG Stable and Evolution, yesterdays update didn't fix this issue. Indicator is set to 14400.0 in our EnhancedGameplay_ServerSettings.json but tiredness reduces to minimum within around 10 minutes while only jogging with x2 server acceleration. Respawning with a fresh character does not solve the problem.

Here is a video proof on a fresh server with only VPPAdminTools, CF, Hellretex Survival and Hellretex Enhanced Gameplay Stable which was only set up for verifying this issue!

At the beginning you can see the default EnhancedGameplay_ServerSettings.json running on the server with the tiredness indicator set to 14400.0 (e.g. 4 hours). In game I started with a fresh character. After 4:50 minutes the tiredness indicator turns yellow, after 9 minutes it turns red and starts blinking after 11:28 minutes.

[https://youtu.be/FCTU-hXZlR0](url)

After this test i connected to four different random servers running either the stable or the evolution version of your mod and it was exactly the same issue on every single server.

I really love your mod and so does our community but at the moment none of the servers running this mod are playable with this issue.

**Comment by davidou2a** [comment] 2021-11-08 12:00
need all logs server **and** client because you use VPP, not me

**Comment by stephanepapin** [comment] 2021-11-08 12:41
Same issue, I've VPP too. Regarding my test this morning, any value on tiredness parameter seem not used.

In attachment, client and server file's logs for this testing session with these parameters :
- `"TirednessDuration": 115200.0,` i.e 32 minutes expected
- Fresh character
- gauge at 50 % = 3m00s
- gauge at 25 % = 6m17s
- gauge blinking 0 % = 8m02

[20111108-ip-88.218.227.8_port-47854.zip](https://github.com/davidou2a/HellRetex_Official/files/7496971/20111108-ip-88.218.227.8_port-47854.zip)

**Comment by MATTvanEAGLE** [comment] 2021-11-08 13:06
I did another test on the server with **ONLY** CF and Hellretex Enhanced Gameplay Stable enabled and with a fresh spawn character. It is exactly the same issue as before even without VPP this time!

Here are the logs and the json you requested:
[Logs.zip](https://github.com/davidou2a/HellRetex_Official/files/7497097/Logs.zip)

**Comment by davidou2a** [comment] 2021-11-08 16:24
after looking your logs except an error about SoftSkills handler (will be fixed but there is no significant) all seems "normal", i trust you when you say you have issue but i have no useful info in these logs, i will again check the code but it will take long time... with no guarantee because on my side all works as intended... will recheck all formula from my auto-scaler in doubt

**Comment by davidou2a** [comment] 2021-11-08 17:36
[h1]Changes/Fixes[/h1]
- Fixed : Bad value on a Math.Clamp() who return a bad value and in some case change the value from the JSON about Tiredness

to summarize a bad value was put on the auto-scaler formula (1000 to be exact) and you have in result 1000sec of time (16min approx) before have an empty level.

after having eliminated all the possibilities which can be long, there remains only the problem...

**Closed** 2021-11-08 17:36 UTC
Labels: bug, fix soon

**Comment by stephanepapin** [comment] 2021-11-08 19:09
does TirednessDuration have max value ?

**Comment by davidou2a** [comment] 2021-12-12 00:57
Documentation please...
